import { runFeedbackPipelineHandler } from "@/server/tools/runFeedbackPipeline";
import { EvaluateAnswerInput } from "@/types/mcp";

export function evaluateAnswerHandler(input: EvaluateAnswerInput) {
  const pipeline = runFeedbackPipelineHandler({
    topic: input.topic,
    question: input.question,
    answer: input.answer,
    genre: input.topic,
  });

  return {
    score: pipeline.quickFeedback.score,
    feedback: pipeline.quickFeedback.summary,
    strengths: pipeline.quickFeedback.strengths,
    improvements: pipeline.quickFeedback.topImprovements,
    rubricNotes: "Generated by multi-tool adaptive analysis.",
  };
}
